DROP TABLE IF EXISTS ODONTOLOGOS; CREATE TABLE ODONTOLOGOS (ID LONG AUTO_INCREMENT PRIMARY KEY, MATRICULA VARCHAR(20) NOT NULL, NOMBRE VARCHAR(30) NOT NULL, APELLIDO VARCHAR(50) NOT NULL);


-- para test --

INSERT INTO ODONTOLOGOS(MATRICULA, NOMBRE, APELLIDO) VALUES ('12345', 'Fulanito', 'Cosme'), ('67890', 'Nemo', 'Payaso'), ('56473', 'Elmer','Grunnion'), ('69960','Nombre4', 'Apellido4');
